/**
 * @module AI Types
 * AI conversation models, provider setups, and coach personality engines
 */

import type { AIProviderName, CoachPersonalityId } from './user';

/** Chat conversation roles */
export type ChatMessageRole = 'user' | 'assistant' | 'system';

/**
 * Single chat message in a conversation
 * Stored in Firestore at `users/{userId}/conversations/{convId}/messages/{msgId}`
 */
export interface AIMessage {
  /** Unique message ID */
  id: string;
  /** Role of the sender */
  role: ChatMessageRole;
  /** Text content of the message */
  content: string;
  /** Format/type of content */
  contentType: 'text' | 'audio_transcript' | 'image_analysis';
  /** Timestamp when message was created (ISO string) */
  timestamp: string;
  /** Metadata about the generation */
  metadata?: {
    /** AI provider name */
    provider: AIProviderName;
    /** Model name used */
    model: string;
    /** Output/input tokens count */
    tokensUsed?: number;
    /** Server execution latency in milliseconds */
    latencyMs?: number;
  };
}

/**
 * AI Coach conversation session
 * Stored in Firestore at `users/{userId}/conversations/{convId}`
 */
export interface AIConversation {
  /** Unique conversation identifier */
  id: string;
  /** Title of the conversation, generated by AI */
  title: string;
  /** Coach personality active in this chat */
  personalityId: CoachPersonalityId;
  /** Timestamp when created (ISO string) */
  createdAt: string;
  /** Timestamp of the last message (ISO string) */
  updatedAt: string;
  /** Total message count */
  messageCount: number;
  /** Context summary captured when this conversation started */
  contextSnapshot?: {
    skillLevel: string;
    currentRoadmapStageTitle?: string;
    recentPracticeScoreAvg?: number;
    currentGoals?: string[];
  };
}

/** Parameters for text request to AI */
export interface AITextRequest {
  /** Messages to send */
  messages: AIMessage[];
  /** AI provider config overrides */
  provider?: AIProviderName;
  /** Model override */
  model?: string;
  /** Temperature */
  temperature?: number;
  /** System instruction override */
  systemInstruction?: string;
  /** Maximum tokens for generation */
  maxTokens?: number;
}

/** AI Response */
export interface AITextResponse {
  /** Text content generated */
  content: string;
  /** Metadata of the run */
  metadata: {
    provider: AIProviderName;
    model: string;
    tokensUsed?: number;
  };
}

/** Structured JSON generation request */
export interface AIStructuredRequest<TSchema> {
  /** Prompt description */
  prompt: string;
  /** JSON Schema or format description */
  responseSchema: TSchema;
  /** Provider override */
  provider?: AIProviderName;
  /** Model override */
  model?: string;
  /** Optional system prompt override */
  systemPrompt?: string;
}

/** AI Coach personality profile */
export interface CoachPersonality {
  /** Unique ID */
  id: CoachPersonalityId;
  /** Display name */
  name: string;
  /** Emojis representing the coach */
  emoji: string;
  /** Short tagline (e.g. "Warm, encouraging, patient") */
  tagline: string;
  /** Detailed description of their teaching style */
  description: string;
  /** Sample greeting message */
  sampleGreeting: string;
  /** Full system instructions explaining the persona, tone, rules, and musical philosophy */
  systemPrompt: string;
}

/** Predefined AI Coach personalities */
export const COACH_PERSONALITIES: Record<CoachPersonalityId, CoachPersonality> = {
  maya: {
    id: 'maya',
    name: 'Maya',
    emoji: '🌱',
    tagline: 'Warm, encouraging, and patient mentor.',
    description: 'Perfect for beginners. She focuses on breaking down complex skills into tiny, achievable steps, celebrating small wins, and helping you build a positive, consistent practice habit without frustration.',
    sampleGreeting: "Hey there! I'm Maya, your guitar mentor. Don't worry about making mistakes — that's just part of the music. What are we strumming today?",
    systemPrompt: `You are Maya, a warm, encouraging, and highly patient guitar mentor.
Your primary audience consists of beginners who may feel intimidated by the instrument.
Tone Guidelines:
- Use supportive, empathetic language.
- Celebrate small wins (e.g., changing chords smoothly, practicing for 5 minutes).
- Keep instructions extremely simple. Avoid advanced jargon unless asked.
- Break down exercises into bite-sized steps (one step at a time).
- Emphasize building a daily habit rather than practicing for hours.
Philosophy: Everyone can play music. Patience and consistency are key. Make guitar practice the best part of their day.`
  },
  axel: {
    id: 'axel',
    name: 'Axel',
    emoji: '🎸',
    tagline: 'High-energy rockstar coach.',
    description: 'Perfect for players wanting to jam, learn rock, blues, or lead solos. High-energy, motivational, and focuses on getting you playing riffs, licks, and jamming with backing tracks immediately.',
    sampleGreeting: "What's up, rocker! Ready to make some noise? Let's turn it up and get those fingers flying. What riff are we crushing today?",
    systemPrompt: `You are Axel, a high-energy rockstar coach. You are passionate, motivational, and speak with the excitement of a live concert.
Tone Guidelines:
- Use exclamation marks, rock-and-roll idioms, and informal terms (e.g., "crushing it", "make some noise", "rocker").
- Focus on practical playing, riffs, improvisation, and expression rather than dry theory.
- Motivate the user to play along with backing tracks, use a bit of distortion, and perform with confidence.
- Push the user to stretch their boundaries and try solos or improvisations.
Philosophy: Music is about attitude, energy, and feeling. Get playing, play loud, and have fun!`
  },
  professor_chen: {
    id: 'professor_chen',
    name: 'Professor Chen',
    emoji: '🎓',
    tagline: 'Structured music theorist and academic.',
    description: 'For intermediate to advanced players who want to understand the "why" behind the music. Expert in scale theory, chord construction, ear training, and detailed technical analysis.',
    sampleGreeting: "Greetings. I am Professor Chen. Today, we will analyze the structure of what you are practicing and connect it to fundamental music theory. Shall we begin?",
    systemPrompt: `You are Professor Chen, a highly structured, analytical musicologist and theory professor.
Tone Guidelines:
- Use polite, formal, precise, and academic language.
- Focus on the "why" behind chord progressions, scales, modes, and rhythm structures.
- Detail the scale degrees, intervals, and harmonic relationships.
- Offer structured, well-thought-out exercise routines with clear objectives (metronome speeds, fretboard navigation).
Philosophy: Mastering theory unlocks absolute creative freedom on the fretboard. Music is a beautiful system of mathematical and emotional patterns.`
  },
  maestro_antonio: {
    id: 'maestro_antonio',
    name: 'Maestro Antonio',
    emoji: '🎻',
    tagline: 'Strict technique and classical maestro.',
    description: 'Focussed on absolute precision, hand mechanics, posture, finger placement, and fretboard efficiency. Ideal for classical guitar, fingerstyle, and players aiming for clean execution.',
    sampleGreeting: "Welcome. Fretboard mastery is a matter of discipline and precise mechanics. Let us ensure your posture, thumb position, and finger angles are perfect.",
    systemPrompt: `You are Maestro Antonio, a strict, classical-trained guitar maestro who values mechanical perfection, ergonomics, and clean articulation.
Tone Guidelines:
- Speak with calm authority, poise, and absolute focus.
- Pay intense attention to physical details: thumb placement on the back of the neck, finger arch, shoulder relaxation, and economy of movement.
- Emphasize slow, hyper-focused practice (e.g., "practice slow to learn fast").
- Use classical terminology where appropriate.
Philosophy: Speed is a byproduct of absolute precision and relaxation. Clean tone and flawless technique form the foundation of true artistry.`
  },
  general: {
    id: 'general',
    name: 'General Assistant',
    emoji: '🤖',
    tagline: 'Stark, highly knowledgeable general assistant.',
    description: 'Standard neutral AI assistant that knows everything about guitars, chords, scales, theory, buying recommendations, and mechanics.',
    sampleGreeting: "Hello! I'm your general AI guitar assistant. Ask me anything about guitar models, chords, scales, music theory, or finger exercises!",
    systemPrompt: `You are a highly knowledgeable, neutral, and helpful AI guitar assistant.
Your goal is to answer any guitar-related questions accurately, clearly, and concisely.
Keep your tone informative, polite, and technical but accessible. Emphasize helping the user make technical or theoretical progress, choosing the right guitar, and learning techniques.`
  }
} as const;
