/**
 * @module Backing Track Types
 * Backing tracks for jamming and improvisation practice
 */

import type { SkillLevel, Genre } from './user';

/**
 * A backing track in the database
 * Stored in Firestore at `backing_tracks/{trackId}`
 */
export interface BackingTrack {
  /** Unique backing track ID */
  id: string;
  /** Title of the backing track */
  title: string;
  /** Primary musical genre classification */
  genre: Genre;
  /** Musical key (e.g. 'A Minor', 'E Major') */
  key: string;
  /** Tempo of the backing track (BPM) */
  tempo: number;
  /** Time signature (e.g. '4/4') */
  timeSignature: string;
  /** Difficulty rating level */
  difficulty: SkillLevel;
  /** Duration of track in seconds */
  durationSeconds: number;
  /** Firebase Storage URL to stream the audio file */
  audioURL: string;
  /** Scales suggested for solo improvisation over this track */
  suggestedScales: string[];
  /** Chords played in the backing track rhythm cycle */
  suggestedChords: string[];
  /** Whether the track was generated by AI */
  isAIGenerated: boolean;
  /** Timestamp when added (ISO string) */
  createdAt: string;
}
