/**
 * @module Song Types
 * Song database representation and AI song generation parameters
 */

import type { SkillLevel, Genre } from './user';

/**
 * Representation of a song section
 * Stored in Firestore at `songs/{songId}/sections/{sectionId}`
 */
export interface SongSection {
  /** Section identifier */
  id: string;
  /** Index position of the section in the song */
  index: number;
  /** Section name (e.g. 'Intro', 'Verse 1', 'Chorus', 'Bridge', 'Outro') */
  name: string;
  /** List of chords played in this section */
  chords: string[];
  /** Strumming pattern description (e.g. 'D-D-U-U-D-U') */
  strummingPattern: string;
  /** Tablature content, if available (custom tab or ASCII format) */
  tabs?: string;
  /** Lyrics text aligned with chords */
  lyrics?: string;
  /** Chords simplified for beginners */
  simplifiedChords?: string[];
  /** Chords/voicing for advanced players */
  advancedChords?: string[];
}

/**
 * A song in the database
 * Stored in Firestore at `songs/{songId}` or `users/{userId}/saved_songs/{songId}`
 */
export interface Song {
  /** Unique song ID */
  id: string;
  /** Title of the song */
  title: string;
  /** Artist / Band name */
  artist: string;
  /** Associated genres */
  genres: Genre[];
  /** Difficulty rating */
  difficulty: SkillLevel;
  /** Musical key (e.g. 'C Major', 'A Minor') */
  key: string;
  /** Tempo in Beats Per Minute (BPM) */
  tempo: number;
  /** Time signature (e.g. '4/4', '3/4', '6/8') */
  timeSignature: string;
  /** Capo fret position, if any (null if no capo) */
  capo: number | null;
  /** Tuning configuration name (e.g., 'standard', 'dropD') */
  tuning: string;
  /** List of chords required to play this song */
  requiredChords: string[];
  /** Techniques required to play this song (e.g. 'palm_muting', 'hammer_on') */
  requiredTechniques: string[];
  /** Estimated hours needed to learn this song */
  estimatedLearningHours: number;
  /** Whether this song was generated by the AI */
  isAIGenerated: boolean;
  /** Whether this song was imported/created by a user */
  isUserGenerated: boolean;
  /** YouTube video tutorial or cover URL */
  youtubeURL?: string;
  /** External tab or sheet source URL */
  sourceURL?: string;
  /** Number of times this song has been learned/practiced in the system */
  timesPracticed: number;
  /** Average user rating (1.0 to 5.0) */
  averageRating?: number;
  /** Timestamp when added (ISO string) */
  createdAt: string;
  /** Timestamp when updated (ISO string) */
  updatedAt: string;
  /** Sections containing lyrics, chords and tabs */
  sections?: SongSection[];
}

/** Parameters passed to AI to generate a custom practice song */
export interface SongGenerationParams {
  /** Prompt description or topic (e.g. "a melancholy blues in A minor") */
  prompt?: string;
  /** Target skill level */
  difficulty: SkillLevel;
  /** Chords to include in the song */
  includeChords: string[];
  /** Techniques to focus on */
  focusTechniques: string[];
  /** Desired genre style */
  genre: Genre;
  /** Key override */
  key?: string;
  /** Tempo override */
  tempo?: number;
  /** Whether to include lyrics */
  includeLyrics: boolean;
}
